(define tarifa '(
 ("Santa Fe" 5 ((10 . 0) (12 . 0) (16 . 0)))
 ("Recreo" 2 ((10 . 20) (12 . 20) (16 . 20)))
 ("Candiotti" 1 ((10 . 30) (12 . 30) (16 . 30)))
 ("Iriondo" 2 ((10 . 35) (12 . 35) (16 . 35)))
 ("Manucho" 2 ((10 . 45) (12 . 45) (16 . 45)))
 ("Cululu" 0 ((11 . 0) (13 . 0) (17 . 0)))
 )
 )

(define val-hor (lambda (salida horarios)
                  (if (null? horarios)
                      (display "error flaco")
                      (let ((hora (caar horarios)) (minutos (cdr (car horarios))) (hs (car salida)) (ms (car (cdr salida))))
                        (if (< hs hora)
                            horarios
                            (if (eqv? hs hora)
                                (if (or (< ms minutos) (eqv? ms minutos))
                                    horarios
                                    (val-hor salida (cdr horarios))
                                    )
                                (val-hor salida (cdr horarios))
                                )
                            )
                        )
                  )))

(define suma (lambda (destino list4)
               (if (null? list4)
                   (display "error flaco tira algo como la gente")
                   (if (eqv? (caar list4) destino)
                       0
                       (+ (car (cdr (car list4))) (suma destino (cdr list4)))
                       )
                   )
               ))
  
(define find (lambda (viaje1 list4)
               (if (null? list4)
                   (display "error")
                   (if (eqv? (caar list4) (car viaje1))
                       (and (display (car viaje1)) (display " - ") (display (car (cdr viaje1)))
                            (display " $") (display (suma (car (cdr viaje1)) list4))
                            (display " - ") (display (val-hor (car (cdr (cdr viaje1))) (car (cdr (cdr (car list4))))))
                            (display "\n"))
                       (find viaje1 (cdr list4))
                       )
                   )
               ))

(define viaje (lambda (viaje1)
                (find viaje1 tarifa)
                ))

(viaje '("Recreo" "Manucho" (12 30)))
(viaje '("Santa Fe" "Cululu" (9 0)))
(viaje '("Santa Fe" "Iriondo" (11 0)))